Mitigate error in `hoverInspect` when entity no longer exists
matter-ecs/matter pull request #103
Opened 2024-08-10 18:30 UTC by Nidoxs

## Proposed changes
Add a check at the top of the `hoverInspect` plasma component to see if the world contains the entity `id` before trying to call `_getEntity`.

## Related issues
Fixes #16.

2024-08-11 00:29 UTC, jackTabsCode requested changes
Are we sure we want to return a no-op widget here, rather than handling this higher up in the debugger?

2024-08-11 00:32 UTC, Nidoxs commented
> Are we sure we want to return a no-op widget here, rather than handling this higher up in the debugger?

This is a fair point, perhaps line 44 of `ui.luau` may be better?

2024-08-11 12:25 UTC, Nidoxs commented
@jackTabsCode I think this is a more appropriate place for the `world:contains` check.

![image](https://github.com/user-attachments/assets/2f6b0a5f-a019-46f3-b318-27442988c576)

2024-08-13 02:08 UTC, jackTabsCode approved these changes

2024-08-13 19:10 UTC, merged