Memoize system names
matter-ecs/matter pull request #134
Opened 2024-10-29 23:12 UTC by jackTabsCode

Only call `systemName()` once, when the system is scheduled.

2024-10-30 00:32 UTC, jackTabsCode commented
Running into an issue with hot reloading
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/975d1360-c6e7-4c3c-9945-9c09f6795a52">
Note for myself

2024-11-14 18:16 UTC, memorycode approved these changes

2024-11-14 18:17 UTC, memorycode requested changes
Changelog needs to be updated before we can merge

2024-11-14 21:43 UTC, memorycode approved these changes

2024-11-15 04:26 UTC, merged