Update CHANGELOG.md
matter-ecs/matter pull request #60
Opened 2024-04-21 22:23 UTC by Ukendio

2024-04-21 22:29 UTC, jackTabsCode approved these changes

2024-04-22 03:00 UTC, LastTalon requested changes

2024-04-22 03:00 UTC, LastTalon commented on CHANGELOG.md
> +## [0.8.0] - 2024-04-21
These should be unreleased until we actually make the release.

2024-04-22 14:20 UTC, jackTabsCode commented on CHANGELOG.md
> +
https://github.com/matter-ecs/matter/pull/54 should be mentioned

2024-04-23 00:15 UTC, jackTabsCode approved these changes

2024-04-23 00:16 UTC, merged